const API_KEY = "724372d799a3cfb28adaa542edab5f25";
const API_URL = "https://api.themoviedb.org/3";
const IMAGE_BASE_URL = "https://image.tmdb.org/t/p/";
const SEARCH_TIMEOUT_SEC = 500;
const INITIAL_ANIMATION_STEP = 500;
const REMOVE_ADDANIMATION_DELAY = 2000;
const REMOVE_ADDANIMATION_STEP = 100;
const HIDE_INTRO_DELAY = 2300;

export {
  API_KEY,
  API_URL,
  IMAGE_BASE_URL,
  SEARCH_TIMEOUT_SEC,
  INITIAL_ANIMATION_STEP,
  REMOVE_ADDANIMATION_DELAY,
  REMOVE_ADDANIMATION_STEP,
  HIDE_INTRO_DELAY,
};
