const API_KEY = "724372d799a3cfb28adaa542edab5f25";
const API_URL = "https://api.themoviedb.org/3";
const IMAGE_BASE_URL = "https://image.tmdb.org/t/p/";
const SEARCH_TIMEOUT_SEC = 500;
const INITIAL_ANIMATION_STEP = 150;
const ADD_FADEANIMATION_STEP = 50;
const REMOVE_FADEANIMATION_DELAY = 2000;
const HIDE_INTRO_DELAY = 2300;

export {
  API_KEY,
  API_URL,
  IMAGE_BASE_URL,
  SEARCH_TIMEOUT_SEC,
  INITIAL_ANIMATION_STEP,
  REMOVE_FADEANIMATION_DELAY,
  ADD_FADEANIMATION_STEP,
  HIDE_INTRO_DELAY,
};
